language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
before_install:
  - sudo apt-get update
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script:
  - python manage.py test animals
