language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
before_install:
  - sudo apt-get update
  - sudo apt-get install libsqlite3-dev
  - sudo apt-get install libspatialite2
  - sudo apt-get install libspatialite-dev
  - sudo apt-get install spatialite-bin
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite
  - pip install -r requirements.txt --use-mirrors
  - wget http://www.gaia-gis.it/spatialite-2.4.0/init_spatialite-2.4.sql.gz
  - gunzip init_spatialite-2.4.sql.gz
  - spatialite straymapperdb < init_spatialite-2.4.sql
script:
  - python manage.py test animals
